Epmlstrtai 153
EvilXa0S/JDI pull request #57
Opened 2017-09-25 15:13 UTC by Crash1048576

prepared back-end for sub-task EPMLSTRTAI-153

2017-09-26 06:49 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/pom.xml
> +            <version>6.11</version>
Remove to the parent xml-file

2017-09-26 08:01 UTC, pomkine commented on Java/JDI/jdi-cucumber-test-generator/pom.xml
> +        <dependency>
are we using testng somewhere?

2017-09-26 08:02 UTC, pomkine commented on Java/JDI/jdi-cucumber-test-generator/src/main/java/com/epam/test_generator/controllers/TagController.java
> +    @RequestMapping(value = "/getAllTags", method = RequestMethod.GET, produces = "application/json")
Please remove verb from path. Change it to something like /tags

2017-09-26 08:07 UTC, pomkine commented on Java/JDI/jdi-cucumber-test-generator/src/main/java/com/epam/test_generator/entities/Tag.java
> +        this.name = name.toLowerCase();
is that a business req?

2017-09-26 08:08 UTC, pomkine commented on Java/JDI/jdi-cucumber-test-generator/src/main/java/com/epam/test_generator/services/TagService.java
> +		for(Tag tag : tags){
you can use java 8 stream here

2017-09-26 08:09 UTC, pomkine commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/popup.js
> +//function PopUpUpdateSuit(){
please remove commented code

2017-09-26 10:17 UTC, kugushev requested changes
I haven't found any checks if an argument is null.

2017-09-26 10:17 UTC, kugushev commented on Java/JDI/jdi-cucumber-test-generator/src/main/java/com/epam/test_generator/dto/TagDTO.java
> +
I suppose you should override toString() method because CaseDTO uses TagDTO

2017-09-26 10:17 UTC, kugushev commented on Java/JDI/jdi-cucumber-test-generator/src/main/java/com/epam/test_generator/services/CaseService.java
> +                tags.add(tag);
Why don't you use Stream API in this case?

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/buttonsExecuting.js
>  function saveCase() {
Please, align code in this function.

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/case/addCase.js
>          addCase: function() {
Please, align code in this function.

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/suit/suitMain.js
> +         var tagsToString = "";
I think it help you:
var arr = [ 1, 2 , 3]
arr.join('+') // "1+2+3"

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/suit/suitMain.js
> +                         var tagsToString = "";
I think it help you:
var arr = [ 1, 2 , 3]
arr.join('+') // "1+2+3"

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/main/webapp/WEB-INF/static/js/suit/suitMain.js
> +        var tagsToString = "";
I think it help you:
var arr = [ 1, 2 , 3]
arr.join('+') // "1+2+3"

2017-09-27 04:44 UTC, FunCat commented on Java/JDI/jdi-cucumber-test-generator/src/test/java/com/epam/test_generator/file_generator/FileGeneratorTest.java
> -public class FileGeneratorTest extends Assert{
Why are you deleting test class???

2017-09-27 09:59 UTC, malginsa approved these changes

2017-09-27 10:20 UTC, merged